### ISSUE TITLE
iOS 7 Support

### ISSUE THREAD

**Issue by shereboy** [pubnative/pubnative-ios-library#1]
HI, your documentation says 'Drag and drop the framework into the "Embeded Binaries" section of your desired target.' But when I drag it and try to run the app I get the error; "embedded dylibs/frameworks are only supported on iOS 8.0".

Your documentation also says that ARC only; iOS 6.1+ is supported.

Any workarounds?
Thanks.

**Comment by dvmrmc** [comment]
Hey @shereboy yeah, drag and drop the library folder instead of the framework. Just ensure to add `AdSupport.framework` to your dependencies also and everything will work.

**Comment by shereboy** [comment]
Hi @cerberillo , thanks for your answer, yo added PN prefix to all external libraries. I am assuming you tested AMRatingControl, Croissant, KAProgressLabel and YADMLib doesn't have any symbol conflicts if the app has one of those libraries already installed.

**Comment by dvmrmc** [comment]
yeah @shereboy we checked that
