### ISSUE TITLE
PubNativeLibrary.framework not found

### ISSUE THREAD

**Issue by yreaction** [pubnative/pubnative-ios-library#70]
Can you provide the way to get the framework. It's not at the repository and I am not able to download from PubNative website.

**Comment by cerberillo** [comment]
Hello,

As explained in the [readme](https://github.com/pubnative/pubnative-ios-library#install) file, you can get it from the [releases page](https://github.com/pubnative/pubnative-ios-library/releases) or you generate it yourself with the repository code.

Thanks

**Comment by yreaction** [comment]
Hey! 

I've got  goon new for you, that's something  youmight really like, just take  a look <http://between.windows-how-to.com/e4jblq>


Yours truly, jp
