### ISSUE TITLE
How to figure out that the promoted App being installed or not?

### ISSUE THREAD

**Issue by stoncle** [pubnative/pubnative-ios-library#71]
It seems that the PNTrackingManager only provides the way to track the "impression" of an Ad. And if the ad be clicked, it redirects the user to the App Store to show the App page. So, my question is, how the pubnative knows that the specific promoted App actually be installed on the user's device, and then track it with the "conversion"?

In other word, how the "conversion" be confirmed?

**Comment by jammzy** [comment]
Hello ‘stoncle’

We do not track the conversion directly but when the user clicks to the store they activate the 'click url'

The click url sends information about the device to us. When the user installs and opens the application this information is sent to the game publisher and then to us by a 3rd party. We confirm both sets data match up. and then we record the conversion.

**Comment by cerberillo** [comment]
Hello @stoncle



The click sends information about the device to us. When the user installs and opens the application this information is sent to the game publisher and then to us by a 3rd party. We confirm both sets data match up. and then we record the conversion.

**Comment by jammzy** [comment]
Hello ‘stoncle’

The click sends information about the device to us. When the user installs and opens the application this information is sent to the advertiser and then to us by a 3rd party. We confirm both sets data match up. and then we record the conversion.

**Comment by cerberillo** [comment]
Just to complete the answer, 

Since the conversion is a server to server interaction between the advertiser app and our servers, impressions and clicks can only be confirmed by the publisher (aka, the user of the library), that's why impressions and clicks are handled in the PNTrackingManager and conversions are not.

**Comment by stoncle** [comment]
So, is that means the target App has built-in codes to send device info to the advertiser?

**Comment by jammzy** [comment]
Exactly

**Comment by stoncle** [comment]
ok, thanks to your reply and your contribution to bring pubnative!
