### ISSUE TITLE
videoCacheQueue property assign/strong ifdef

### ISSUE THREAD

**Issue by Fl0p** [pubnative/pubnative-ios-library#72]
You have such string in 
https://github.com/pubnative/pubnative-ios-library/blob/7257d7dc9180cd38f33826cbf963439fb57aec3b/PubNativeLibrary/PubNativeLibrary/Components/Common/Video/PNVideoCacher.m#L37
```objC
@property (nonatomic, strong) dispatch_queue_t  videoCacheQueue;
```
it should look like:
```objC
#if OS_OBJECT_HAVE_OBJC_SUPPORT == 1
@property (nonatomic, strong) dispatch_queue_t  videoCacheQueue;
#else
@property (nonatomic, assign) dispatch_queue_t  videoCacheQueue;
#endif
```
For any os versions

**Comment by cerberillo** [comment]
I don't agree, since as explained in [requirements](https://github.com/pubnative/pubnative-ios-library#requirements):

* ARC only; iOS 6.0 and above

**Comment by Fl0p** [comment]
okay.jpg
