### ISSUE TITLE
Archive upload failed with errors (Xcode 7.3.1)

### ISSUE THREAD

**Issue by zetxek** [pubnative/pubnative-ios-library#78]
When trying to upload one application with PubNative 1.4.0 setup, and working in development, these errors are received in the iTunes validation phase:

> ERROR ITMS-90087: "Unsupported Architectures. The executable for XXX.app/Frameworks/PubNativeLibrary.framework contains unsupported architectures '[x86_64, i386]'."
> ERROR ITMS-90087: "Unsupported Architectures. The executable for XXX.app/Frameworks/PubNativeLibrary.framework contains unsupported architectures '[x86_64, i386]'."
> 
> ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle XXX.app/Frameworks/PubNativeLibrary.framework is invalid. The minimum value is 8.0"
> ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle XXX.app/Frameworks/PubNativeLibrary.framework is invalid. The minimum value is 8.0"
> 
> ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XXX.app/Frameworks/PubNativeLibrary.framework/PubNativeLibrary' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
> ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XXX.app/Frameworks/PubNativeLibrary.framework/PubNativeLibrary' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
> 
> ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
> ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
> 
> WARNING ITMS-90080: "The executable 'Payload/XXX.app/Frameworks/PubNativeLibrary.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
> WARNING ITMS-90080: "The executable 'Payload/XXX.app/Frameworks/PubNativeLibrary.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

**Comment by zetxek** [comment]
The problem was solved used the source code copied to my project, instead of using the framework.

For reference, my project is made in Swift.

**Comment by psychocandy** [comment]
Thanks @zetxek, glad we could help and that it finally worked.

We plan to have a more elegant solution in the next version so we will keep you posted.
